Association revenue page
weatherxm-network/weatherxm-network.github.io pull request #36
Opened 2024-12-17 10:37 UTC by vrypan

2024-12-17 10:45 UTC, PavlosTze requested changes

2024-12-17 10:45 UTC, PavlosTze commented on docs/association-revenue.md
> +- **Data Licensing Fees**: Fees collected through [data license auctuons](/docs/data-licensing.html).
Typo in "auctuons"

2024-12-17 11:59 UTC, ipanagiv approved these changes

2024-12-30 11:22 UTC, nikil511 approved these changes

2024-12-30 11:23 UTC, merged